### ISSUE TITLE
List of features of cover.

### ISSUE THREAD

**Issue by hemanth** [hemanth/coffeescript-equivalents-in-es6#6]
- [x] Loops and Comprehensions
- [x] Array Slicing and Splicing
- [x] Everything is an Expression
- [x] Operators and Aliases
- [x] Classes, Inheritance, and Super
- [x] Destructuring Assignment
- [x] Function Binding
- [x] Chained Comparisons
- [x] String Interpolation, Block Strings, and Block Comments
- [x] Block Regular Expressions
- [x] Ranges.

**Comment by shawndumas** [comment]
Ranges?

**Comment by hemanth** [comment]
Added to the list :)

**Comment by shawndumas** [comment]
:+1:

**Comment by hemanth** [comment]
PRs welcomed ;)

**Comment by dead-claudia** [comment]
@hemanth Mind updating this checklist?

**Comment by hemanth** [comment]
@impinball Done, any other to item to be checked in the list?

**Comment by dead-claudia** [comment]
@hemanth That TODO list is done, now that I took a good look at it.
- [Loop comprehensions](https://github.com/hemanth/coffeescript-equivalents-in-es6#array-comprehensions)
- Array [slicing](https://github.com/hemanth/coffeescript-equivalents-in-es6#array-slicing) and [splicing](https://github.com/hemanth/coffeescript-equivalents-in-es6#array-splicing)
- [Operators and aliases](https://github.com/hemanth/coffeescript-equivalents-in-es6#operators-and-aliases)
- [Chained comparisons](https://github.com/hemanth/coffeescript-equivalents-in-es6#chained-comparisons) (bad anchor link fixed in #12)
- [Block regular expressions](https://github.com/hemanth/coffeescript-equivalents-in-es6#block-regular-expressions) (incorrect translation fixed in #13)
- [Ranges](https://github.com/hemanth/coffeescript-equivalents-in-es6#ranges)

This bug is probably safe to close.

**Comment by hemanth** [comment]
Wow! lost track of this, thanks @impinball :+1:
